### ISSUE TITLE
Same filenames are not allowed.

### ISSUE THREAD

**Issue by owensd** [AnarchyTools/atbuild#10]
```
Building package atbuild...
Running task default...
<unknown>:0: error: unable to build node: '.atllbuild/Tokenizer.swift.o' (node is produced by multiple commands; e.g., '<atllbuild-swiftc>' and '<atllbuild-swiftc>')
Compiling Swift Module 'atbuild' (15 sources)
<unknown>:0: error: filename "Tokenizer.swift" used twice: 'src/clj/Tokenizer.swift' and 'src/yaml/Tokenizer.swift'
<unknown>:0: note: filenames are used to distinguish private declarations with the same name
<unknown>:0: error: build had 1 command failures
fatal error: 'try!' expression unexpectedly raised an error: atbuild.AnarchyBuildError.ExternalToolFailed("/Library/Developer/Toolchains/swift-latest.xctoolchain/usr/bin/swift-build-tool -f .atllbuild/llbuild.yaml"): file /Users/buildnode/jenkins/workspace/oss-swift-package-osx/swift/stdlib/public/core/ErrorType.swift, line 53
```

We'll need to support same filenames in different paths.

**Comment by drewcrawford** [comment]
I probably need to reverse-engineer how SwiftPM handles this situation.  There's probably some deficiency in our sbt emission, or else we may need to file this as a bug in swift-llbuild.

**Comment by drewcrawford** [comment]
Upstream bug.  Opened [SR-543](https://bugs.swift.org/browse/SR-543).

It's conceivable we could work around this in some way, but it's going to be bad.

**Comment by owensd** [comment]
Well that's just awesome... I've already worked around it: I renamed the file. ;)

**Comment by drewcrawford** [comment]
If we accumulate a lot of bugs upstream in llbuild, we could always write a tool that lets you shell to swiftc ourselves.  Really what we would lose is the parallelization.

It's probably not worth it for one easily workaroundable bug, but something to keep in mind.

**Comment by drewcrawford** [comment]
Per SR-543, this goes all the way to the compiler.  You can't have two files with the same name in a Swift module.  Who knew?

Motion to close as "out of scope"?

**Comment by owensd** [comment]
Well that is just the stupidest thing I've seen lately...

Sure enough:

```
10:30:52 › swiftc foo/Tokenizer.swift bar/Tokenizer.swift main.swift 
<unknown>:0: error: filename "Tokenizer.swift" used twice: 'foo/Tokenizer.swift' and 'bar/Tokenizer.swift'
<unknown>:0: note: filenames are used to distinguish private declarations with the same name
```
