### ISSUE TITLE
CI

### ISSUE THREAD

**Issue by drewcrawford** [AnarchyTools/atbuild#11]
We need CI of some sort, across Linux and OSX.

I have a system I use for code.sa, but I'm not sure how easy it is to make it work here also.  May look into Travis instead.

**Comment by drewcrawford** [comment]
- Travis doesn't (by default) allow multi-OS builds.  I have an email into their support.  It's unclear to me if I can install the 2.2 snapshots there.
- CircleCI doesn't support El Capitan
- I run my own Gitlab instance to work around this shit ordinarily, but because this is hosted on GitHub, it doesn't integrate there.

**Comment by dunkelstern** [comment]
I have a gitlab ci instance running on my server, linux builds would be possible there. For OSX i could ask in my company we have a ci server running there.
