### ISSUE TITLE
The output paths need to be supported via substitution variables.

### ISSUE THREAD

**Issue by owensd** [AnarchyTools/atbuild#17]
`script: "./.atllbuild/products/atpkgtests"`

Need values to use, like `${TARGETDIR}` or something.

**Comment by drewcrawford** [comment]
Should we
1.  Export this into shell
2.  Do some kind of find/replace at the manifest level
3.  ???

**Comment by owensd** [comment]
At the very least #2. It would probably be nice to expose them to env variables so that an external tool could get those values as well. We need to make sure we invoke the shell target properly to inherent the env too.

**Comment by drewcrawford** [comment]
This problem goes beyond shell, for example, our new `xctestrun` command also is typically mucking around in the `atllbuild` products directory.  So shell environment variables don't really solve the problem.

I think we just need to export built products into `./bin/`.
