### ISSUE TITLE
Add support for both name and module-name.

### ISSUE THREAD

**Issue by owensd** [AnarchyTools/atbuild#27]
We should provide a way to set both the `name` and `module-name`. The `name` is used to determine what the actual filename is on disk, while the `module-name` allows for setting what the import package name will surface as.

The default should be `module-name` = `name`.

**Comment by drewcrawford** [comment]
I believe the correct resolution here is to preserve the `name` behavior and introduce `executable-name`.

Frameworks are named the same as the modules they contain, so executables are the "odd man out" here.
