### ISSUE TITLE
2.2, 3.0, and Xcode.

### ISSUE THREAD

**Issue by drewcrawford** [AnarchyTools/atbuild#58]
One of the troubles we face is how to migrate out of "unstable" Swift.  Either as a target (we build user projects for Swift 2.2 "release channel") or as a development process (we build atbuild _with_ Swift 2.2 "release channel").

OSX users are likely to get their Swift with Xcode, and we currently don't support "Xcode Swift" (since the 2.2 toolchain won't be available until Xcode 7.3.)

On top of that, the `swift-build-tool`, an `atllbuild` dependency, is not available in the "release" channel (they're shipping in 3.0) and so it will never be available in Swift 2.x "release" or Xcode 7.x.

Our options here are:
1.  Require all downstream users to use development Swift snapshots.  This seems bad.
2.  If we want to support Swift 2.2 "release channel" then we need to vendor our own swift-build-tool that users can install separately.
3.  Then there is the question of how we know which toolchain to use.  Currently on OSX we are hardcoded to `Latest` and on Linux we use `/usr/local/bin/swiftc`.  That doesn't sound right.
   
   I think on OSX the "right" behavior is to use `xcrun` et al.  Then if the user wants to use an open toolchain Xcode 7.3 has a picker, and `xcrun` respects the picker's choice.
   
   On Linux I'm not sure what the right answer is.  Can we rely on `/usr/local/bin` in that case?

**Comment by owensd** [comment]
> 1. Require all downstream users to use development Swift snapshots. This seems bad.

I'm actually ok with this limitation until Swift 2.2 is shipped... and maybe even 3.0. Is there a compelling reason for us to do the work for that? It seems like it would be throw-away work.

> 2. If we want to support Swift 2.2 "release channel" then we need to vendor our own swift-build-tool that users can install separately.

If we did this, it should be simply part of the Anarchy Tools download along side `atbuild` and `atpm`. But again, this sounds like throw-away work for the short term. I guess it really depends on when Swift 3.0 will release.

> 3. Then there is the question of how we know which toolchain to use. Currently on OSX we are hardcoded to Latest and on Linux we use /usr/local/bin/swiftc. That doesn't sound right.
> 
> I think on OSX the "right" behavior is to use xcrun et al. Then if the user wants to use an open toolchain Xcode 7.3 has a picker, and xcrun respects the picker's choice.
> 
> On Linux I'm not sure what the right answer is. Can we rely on /usr/local/bin in that case?

I don't think `xcrun` is correct. My Xcode builds use a different Swift version than what I develop with locally from the shell.

On Linux, I happen to create links in `/usr/local/bin`, but there is no standard for this and the Swift drops provide no guidance.

Regardless, the path problem is what platform profiles/overlays are for. In our package files, these are currently hard-coded. However, the intention is that there would be system and user packages that could provide the tool the information of the locations for things we need. We just need to add that support. ;)

The lookup paths should be something like:
- `/etc/anarchtools/system.atpkg` - a system wide setting
- `~/.anarchytools/user.atpkg` - a user defined set of settings

**Comment by drewcrawford** [comment]
>  Is there a compelling reason for us to do the work for that? It seems like it would be throw-away work.
1.  Maintaining the snapshots is a big drain for me.  It is a necessary drain, right now, but it might not be when 2.2 ships.  It depends on what other projects I have that actually require Swift 3.  If I maintain my Foundation dependency I might stay on snapshots, but it is at least possible that I will not.
2.  I don't have good visilbity into my "day job roadmap" right now but it seems possible I will end up shipping a product with atbuild/Swift 2.2.  In that case, it becomes more a question of what kind of solution we want to merge, rather than whether I will produce one.  But at this point it's more in the stages of planning for what might happen.

> I guess it really depends on when Swift 3.0

I understand 2.2 to be probably "march/april" whereas 3.0 will be "november/december".  

> My Xcode builds use a different Swift version than what I develop with locally from the shell.

Why?

> The lookup paths should be something like

We could certainly do this.  It does break convention with carthage/cocoapods/everybody else who respect the xcrun setting.  It has become a convention for OSX.  Is there a compelling reason to ignore it?

**Comment by owensd** [comment]
> >  Is there a compelling reason for us to do the work for that? It seems like it would be throw-away work.
> 1.  Maintaining the snapshots is a big drain for me.  It is a necessary drain, right now, but it might not be when 2.2 ships.  It depends on what other projects I have that actually require Swift 3.  If I maintain my Foundation dependency I might stay on snapshots, but it is at least possible that I will not.

I could see us locking at Swift 2.2.

> > My Xcode builds use a different Swift version than what I develop with locally from the shell.
> 
> Why?

Because my Xcode drops use the RTM bits and not pre-release. I don't hand out builds built on non-RTM tools.

> > The lookup paths should be something like
> 
> We could certainly do this.  It does break convention with carthage/cocoapods/everybody else who respect the xcrun setting.  It has become a convention for OSX.  Is there a compelling reason to ignore it?

Well I pretty much dislike all conventions of Carthage and CocoaPods ;). We can default to the `xcrun`, but I need a way to consistently override it though so I can build with the toolchains and not have to use Xcode fix up stuff. Heck, I don't even think I've downloaded the latest Xcode 7.3 builds...

**Comment by drewcrawford** [comment]
> Because my Xcode drops use the RTM bits and not pre-release. I don't hand out builds built on non-RTM tools.

That explains your current practice, but not why in April 2016 Swift 2.2 would not be RTM for you.  I mean, I suppose I can imagine you are stuck on an old version for some reason.

> We can default to the xcrun, but I need a way to consistently override it though so I can build with the toolchains and not have to use Xcode fix up stuff.

We can, I may need the user.atpkg / system.atpkg for other reasons anyway, so if this is useful for you for this problem it may not be far out of my way, depending on exactly how my roadmap shifts for my other projects.
