### ISSUE TITLE
`fatalError` crashes the app with a backtrace on compiler error message

### ISSUE THREAD

**Issue by dunkelstern** [AnarchyTools/atbuild#72]
This is indeed very good if i want to debug `atbuild` but it clobbers build output if i do not want to debug `atbuild` or if the swift compiler fails with an error message (which is probably not `atbuild`s fault)

**Comment by drewcrawford** [comment]
What behavior do you expect here?

We could `exit(42)` I suppose.

**Comment by dunkelstern** [comment]
Crashing like we do currently is bad because it is logged in the kernel log on linux too ;)
Just exiting for non-debug builds seems fine to me (at least where we use `fatalError` currently, real exceptions should raise a trace like normal i think)
