### ISSUE TITLE
Switch to clojure-based syntax

### ISSUE THREAD

**Issue by drewcrawford** [AnarchyTools/atbuild#8]
Per Slack, @owensd is contributing a parser for the clojure syntax.  The thinking is it better handles the append/replace distinction.

I'm going to continue sailing along with YAML until that is merge-ready but it is a better syntax for this problem.

**Comment by drewcrawford** [comment]
So.  Our YAML library (in addition to its many other failings, lol) requires NSRegularExpression which isn't implemented at all in corelibs-foundation.

Implementing Boyer-Moore and PRing it upstream is hard.  Instead, I suggest we block Linux support #1 on this issue.

Any ETA?

**Comment by owensd** [comment]
I'll have the tokenizer done today. Probably get the parser started as well.

**Comment by owensd** [comment]
Fixed in commit 0476fc3.
