### ISSUE TITLE
Keeping build up-to-date?

### ISSUE THREAD

**Issue by owensd** [AnarchyTools/atbuild#9]
What's the story with the project system? We currently have three (Xcode, swift-build-tool, and atbuild). Do you expect us to keep all three up-to-date?

**Comment by drewcrawford** [comment]
I use xcode to develop right now, but I don't actually care if anyone breaks it.  I can fix it, if I'm the only one using it.  It's mostly there for my convenience.  Someday we should get an emit-xcode thing.

We should keep `atbuild` from breaking.  I am going to set up CI of some description #11, but I think Linux support is a higher priority.

`swift-build-tool` is necessary to build `atbuild` from scratch, so we should keep that working too, or at least check it occasionally.  It's actually as simple as running `atbuild bootstrap`, so it's mostly a case of keeping `atbuild` working.

**Comment by drewcrawford** [comment]
Resolved via CI, if CI is happy, we're happy.
