### ISSUE TITLE
Unhelpful error messages when submodules missing

### ISSUE THREAD

**Issue by owensd** [AnarchyTools/atbuild#90]
I was pulling down some `atpkg` updates on my laptop, which had not been updated in a while so it didn't have the submodules yet.

When performing the build from the command line (`atbuild v1.0`), all I saw was this:

```
9:48:41 › atbuild -f build.atpkg check
enabling overlays ["atbuild.platform.osx", "atbuild.platform.mac"]
Could not load package file: NoSuchEntity
atbuild - Anarchy Tools Build Tool 1.0
https://github.com/AnarchyTools
© 2016 Anarchy Tools Contributors.

Usage:
atbuild [--toolchain (/toolchain/path | xcode)] [-f packagefile] [task] [--clean]
No tasks are available; run --help in a directory with a build.atpkg for project-specific help
```

I was really confused.

Turned out the issue was that I was missing the `atfoundation` submodule. After properly getting that, the build was working again.

We should provide some better error message here when the `import-packages` files cannot be found.

**Comment by owensd** [comment]
I see that there is this: `Could not load package file: NoSuchEntity`. However, that message is lost in the mini-wall-of-text, and also doesn't point to the the problem: `atfoundation/build.atpkg` was missing.

**Comment by dunkelstern** [comment]
It would be much clearer if we used the package manager for dependency resolution. See proposal here: https://github.com/AnarchyTools/atbuild/issues/91

**Comment by drewcrawford** [comment]
See also https://github.com/AnarchyTools/atfoundation/issues/9, which I believe would significantly improve this error

**Comment by dunkelstern** [comment]
AnarchyTools/atfoundation#9 has been merged, is there something that we can do here in addition to that?
